jobs:
- job: test_suite
  displayName: Test suite
  pool:
    name: Hosted macOS
  steps:
  - template: scripts/ci/common-setup.yml
  - script: yarn run test
    displayName: Run test suite

- job: index_source
  displayName: Rich code navigation indexer
  pool:
    name: Hosted VS2017
  steps:
  - template: scripts/ci/common-setup.yml

  - task: MS-RichCodeNav.Indexer.build-task.RichCodeNavIndexer@0
    displayName: 'Rich Code Navigation Indexer'
    inputs:
      serviceConnection: 'Rich Code Navigation'
      languages: typescript
      githubServiceConnection: 'GitHub Pull Request'
      nugetFeed: 'https://vside.myget.org/F/buildtools/api/v3/index.json'
      serviceEndpoint: 'https://prod.richnav.vsengsaas.visualstudio.com'
